### ISSUE TITLE
Cont.. Secrets Issue since the other thread was closed..

### ISSUE THREAD

**Issue by monubamb** [dockersamples/newsletter-signup#3]
Thanks. That worked. I am at the final stage. Got my services up and running but have few outstanding issues..Issue1 - My Web app cannot be accessed over Swarm IP (which in my case is 172.17.4.4 - says page cannot be displayed. So I had to do docker network inspect to get the NAT IP and access it that way..Issue 2 - More critical... I am not able to access the DB using NAT IP as well from SSMS. Also dont see Prospects table created.. So somehow the web is not able to talk to DB even though I did find secrets folder with password on C:/programdata/docker/secrets on DB container.. I see this UI but data is not populated as far as I can tell..

https://user-images.githubusercontent.com/333392/28086176-fb05c062-6632-11e7-88f6-39e2819e55e5.png

https://user-images.githubusercontent.com/333392/28086299-5be987f6-6633-11e7-96a6-e42271f36cef.png

**Comment by sixeyed** [comment]
I've just tried the stack on a fresh environment and the web app is accessible externally using the Docker server IP address (the host address). Have you got any other services using port 80 on the host? Maybe try publishing to a different port in the stack file.

On the SQL front, if you connect to the Docker host running the database container and get the ID of the container, you can run `Invoke-SqlCmd` inside the container to verify the data is there:

```
docker container exec <container-id> powershell "Invoke-SqlCmd -Query 'SELECT * FROM Prospects' -Database SignUp"
```

You should see the data there. Also run `docker service logs` on the save-handler service and you should see output from the rows being written.

**Comment by sixeyed** [comment]
@monubamb LMK if you still have issues. I've run the sample on multiple environments without problems.
